### ISSUE TITLE
Adjust logger settings

### ISSUE THREAD

**Issue by alexschomb** [pixeltrix/prowler#2]
Is there a simple way to adjust the settings for the 'logger' gem used by prowler? I'd like to change the log location from STDOUT to a textfile.

**Comment by pixeltrix** [comment]
You can set the logger in your configure block:

``` ruby
Prowler.configure do |config|
  config.logger = Logger.new('path/to/logfile')
end
```

If that doesn't work please let me know as it's certainly meant to.

**Comment by alexschomb** [comment]
Thanks for your help, that did the job. Sorry for my late reaction, I simply forgot to answer.
